name: 'TEN | X | I0'
favicon: null
layout_spectrum: 0.7584265624172986
typography_spectrum: 0.5880707518663257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9029018871951848
  lightness: 0.32376807858236134
  saturation: 0.6589880734682083
  rhythmicContrast: 0.5223344785626978
purpose: []
